name: Release

on:
  push:
    tags:
      - "*"

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  release:
    name: Cross build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: mipsel-unknown-linux-musl
            exe: rathole
            cross: true
            
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.71
          default: true
      
      - name: Install OpenSSL
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install pkg-config libssl-dev

      # Cross build
      - name: Install cross
        if: matrix.cross
        run: cargo install --version 0.2.5 cross
      - name: Run tests
        if: matrix.cross
        run: cross test --release --target ${{ matrix.target }} --verbose --no-default-features --features client
      - name: Build release
        if: matrix.cross
        run: cross build --release --target ${{ matrix.target }} --features client --no-default-features
      # - name: Build release with Cargo
      #   if: matrix.cross
      #   run: cargo build --target mipsel-unknown-linux-musl --profile minimal --no-default-features --features client
      - name: Run Strip
        run: strip target/${{ matrix.target }}/release/${{ matrix.exe }}
      - name: Run UPX
        continue-on-error: true
        uses: crazy-max/ghaction-upx@v1
        with:
          version: v4.0.2
          files: target/${{ matrix.target }}/release/${{ matrix.exe }}
          args: -q --best --lzma ${{ matrix.exe }}/rathole

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.1
        with:
          type: zip
          filename: rathole-${{ matrix.target }}.zip
          directory: target/${{ matrix.target }}/release/
          path: ${{ matrix.exe }}
      - name: Publish
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/${{ matrix.target }}/release/rathole-${{ matrix.target }}.zip
          generate_release_notes: true
          draft: true
